workflows:
  android-cliente-workflow:
    name: FINA-AUTO Cliente APK
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      flutter: 3.19.6
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
    scripts:
      - name: Localizar e Compilar o App Cliente
        script: |
          # Procura a pasta correta do cliente que contém o projeto Flutter
          cd $(find . -maxdepth 2 -type d -name "fina_auto_cliente" | head -n 1)
          flutter clean
          flutter pub get
          flutter build apk --release
    artifacts:
      - "**/build/app/outputs/flutter-apk/**/*.apk"

  android-profissional-workflow:
    name: FINA-AUTO Profissional APK
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      flutter: 3.19.6
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
    scripts:
      - name: Localizar e Compilar o App Pro
        script: |
          # Procura a pasta correta do profissional que contém o projeto Flutter
          cd $(find . -maxdepth 2 -type d -name "fina_auto_pro" | head -n 1)
          flutter clean
          flutter pub get
          flutter build apk --release
    artifacts:
      - "**/build/app/outputs/flutter-apk/**/*.apk"